---
title: "DOC_MERGE"
---

## Load data
### DOC

```{r}
#| warning: false

library(tidyverse)
library(readxl)
library(lubridate)

DOC <- read_xlsx("data/DOC2020-2023.xlsx")
DOC$Date <- dmy(DOC$Date)
DOC$Treatment <- as.factor(DOC$Treatment)
glimpse(DOC)
```
```{r,fig.width=10,fig.height=4}
DOC %>% 
    group_by(Date,Treatment) %>% 
    transmute(TOC = mean(TOC,na.rm = T)) %>% 
    ggplot(aes(Date,TOC))+
    geom_bar(aes(fill =  Treatment),
             stat="identity",
             position=position_dodge())+
    geom_smooth(aes(fill=Treatment,color = Treatment))+
    facet_wrap(year(Date)~.,scales = "free_x",ncol = 4)+
    
    theme_bw()+
    scale_fill_manual(values=c("#1a9850", "#fee08b", "#f46d43"))
    scale_color_manual(values = c("#1a9850", "#fee08b", "#f46d43"))
    
```


```{r}
DOC %>% 
    filter(Period == "Pre-treatment") %>% 
    group_by(ID) %>% 
    transmute(TOC_m = mean(TOC,na.rm = T),
              TC_m = mean(TC,na.rm = T),
              IC_m = mean(IC,na.rm = T),
              TN_m = mean(TN,na.rm = T),
              TCN_m = mean(TCN,na.rm = T)) %>% 
    unique.data.frame() -> DOC_Cov
#%>% 
    #glimpse()

```
```{r}
DOC %>% 
    filter(Period != "Pre-treatment") %>% 
    merge(DOC_Cov,by = "ID",all = T) %>% 
    unique.data.frame() -> DOC_full

```

## pH
```{r}
pH <- read_csv("data/PH2020-2023.csv")
glimpse(pH)
```

```{r}
pH %>% 
    filter(Period == "Pre-treatment") %>% 
    group_by(ID) %>% 
    transmute(pH_mean = mean(pH,na.rm = T)) %>% 
    unique.data.frame() -> pH_Cov
```
```{r}
pH %>% 
    filter(Period != "Pre-treatment") %>% 
    merge(pH_Cov,by = "ID",all = T) %>% 
    unique.data.frame() -> pH_full
```

## merge
```{r}
DOC_Ph_full <- merge(DOC_full,pH_full,
                     by = c("ID","Date","Set","Year","Block","Plot",
                             "Treatment","Period","Slope","SLayer"))
```
```{r}
write.csv(DOC_full,"DOC_full.csv",row.names = F)
write.csv(pH_full,"pH_full.csv",row.names = F)
```

# modeling
## LMMS

```{r}

```

